language: php
php:
#  - 5.2
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer install --prefer-dist
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot; fi

script: vendor/bin/phpunit --color EActiveRecordRelationBehaviorTest.php

notifications:
   email: "mail@cebe.cc"
