<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Wednesday 23rd of July 2014 01:07:11 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://localhost/APL/index.php/user/login/oauth", 

		//"base_url" => "https://tompanther.arvixe.com/~webside/yetgroup.com/demo-webserver/APL/index.php/user/login/oauth", 
		"providers" => array ( 
			// openid providers
//			"OpenID" => array (
//				"enabled" => true
//			),
//
//			"AOL"  => array ( 
//				"enabled" => true 
//			),
//
//			"Yahoo" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" )
//			),
//
//			"Google" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" )
//			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "470579799712118", "secret" => "603ece206500ba591cbd3aaba30281cc" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "0uvgR9TunBDD9ugV8ws46xYXb", "secret" => "tu0F0lybbPRBIL0qnbzWFfyqYqQkB6sBgJUlwBOUPEg5w7TBim" ) 
			),

//			// windows live
//			"Live" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" ) 
//			),
//
//			"MySpace" => array ( 
//				"enabled" => true,
//				"keys"    => array ( "key" => "", "secret" => "" ) 
//			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "771y4v85zbk8kt", "secret" => "4JkmTIpHPAjq1p1t" ) 
			),
//
//			"Foursquare" => array (
//				"enabled" => true,
//				"keys"    => array ( "id" => "", "secret" => "" ) 
//			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
